FROM ubuntu:23.10

RUN apt update \
 && apt install -y curl sudo postgresql build-essential golang libavformat-dev libswscale-dev libgraphicsmagick1-dev optipng \
 && curl -fsSL https://deb.nodesource.com/setup_current.x | bash - && apt install -y nodejs \
 && apt clean

EXPOSE 8001
ENV TZ=Europe/Moscow
VOLUME /var/lib/postgresql/data
WORKDIR /cutechan
